using JuMP
using MosekTools
problem=Model(Mosek.Optimizer)
@variable(problem,PG1)
@variable(problem,PG2)
@variable(problem,Pl1)
@variable(problem,Pl2)
@variable(problem,Pl3)
@constraint(problem,0<=PG1<=4)
@constraint(problem,0<=PG2<=3)
@constraint(problem,0<=Pl1<=1)
@constraint(problem,0<=Pl2<=4)
@constraint(problem,1<=Pl3<=3)
@constraint(problem,PG1+PG2-Pl3==4)
@constraint(problem,Pl1+Pl2==4)
@objective(problem,Min,PG1^2+4*PG1+3*PG2^2+2*PG2)
optimize!(problem)
println("PG1= ",value(PG1))
println("PG2= ",value(PG2))
println("Pl1= ",value(Pl1))
println("Pl2= ",value(Pl2))
println("Pl3= ",value(Pl3))